// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://dribbble.com/shots/23027887-Coursue-Learning-Platform-Dashboard
// Generated: 2026-06-05T15:52:51.927Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#0d0c22' | '#000000' | '#060318' | '#ffffff' | '#6e6d7a' | '#655c7a' | '#3d3d4e' | '#9e9ea7' | '#e7e7e9' | '#524b63' | '#262627' | '#f3f3f6' | '#3e34d3' | '#dbdbde' | '#807ea3' | '#ea4c89' | '#727ac0' | '#9890ac' | '#4daa57' | '#808080';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Mona Sans' | 'Times' | 'Arial';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '500' | '700' | '450';

export type SpacingToken = '1px' | '4px' | '24px' | '30px' | '36px' | '40px' | '50px' | '56px' | '60px' | '64px' | '70px' | '80px' | '120px' | '260px';

export type RadiusToken = '3px' | '6px' | '10px' | '16px' | '50px';

export type DurationToken = '50ms' | '100ms' | '200ms' | '300ms' | '450ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
